FROM node:18-slim

WORKDIR /app

RUN apt update && apt install -y python3 make gcc g++ git
COPY package.json package-lock.json  /app/
RUN npm install --legacy-peer-deps

COPY . .
RUN yarn build

EXPOSE 5001

CMD ["npm", "run", "start"]

#CMD ["tail", "-f", "/dev/null"]
